using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEditor;

namespace NAOR.Editor
{
    // Auto-slices sprite sheets generated by AIPipeline/generate_sprite.py
    // (Phase 6.4) using the JSON sidecar written next to the sheet by
    // AIPipeline/src/pack_sprites.py (`<sheet>.png.meta.json` -- distinct
    // from Unity's own `<sheet>.png.meta` asset metadata file).
    public class AutoSpriteImporter : AssetPostprocessor
    {
        [Serializable]
        private class SpriteSheetMeta
        {
            public int cell_size;
            public int cols;
            public int rows;
            public int frame_count;
            public int fps;
            public int sheet_width;
            public int sheet_height;
            public int padding;
            public string[] source_frames;
        }

        private static bool IsGeneratedSheet(string assetPath)
        {
            return assetPath.Contains("Art/Sprites/Generated") && assetPath.EndsWith(".png");
        }

        private static SpriteSheetMeta LoadSidecar(string assetPath)
        {
            string sidecarPath = assetPath + ".meta.json";
            if (!File.Exists(sidecarPath))
            {
                return null;
            }
            try
            {
                string json = File.ReadAllText(sidecarPath);
                return JsonUtility.FromJson<SpriteSheetMeta>(json);
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[AutoSpriteImporter] Failed to parse sidecar {sidecarPath}: {e.Message}");
                return null;
            }
        }

        void OnPreprocessTexture()
        {
            if (!IsGeneratedSheet(assetPath))
            {
                return;
            }

            TextureImporter importer = (TextureImporter)assetImporter;
            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Multiple;
            importer.filterMode = FilterMode.Point;
            importer.textureCompression = TextureImporterCompression.Uncompressed;
            importer.mipmapEnabled = false;
            importer.alphaIsTransparency = true;

            SpriteSheetMeta meta = LoadSidecar(assetPath);
            if (meta == null || meta.cols <= 0 || meta.rows <= 0 || meta.cell_size <= 0 || meta.frame_count <= 0)
            {
                Debug.Log($"[AutoSpriteImporter] No usable sidecar for {assetPath}; leaving default sprite import "
                          + "(configure the grid manually in the Sprite Editor).");
                return;
            }

#pragma warning disable CS0618 // TextureImporter.spritesheet is the simplest API that still works for headless/import-time grid slicing.
            var spriteMetas = new List<SpriteMetaData>();
            int index = 0;
            for (int row = 0; row < meta.rows && index < meta.frame_count; row++)
            {
                // pack_sprites.py lays frames out row-major, frame 0 at the
                // TOP-left of the sheet. Unity's sprite rects use a
                // bottom-left origin, so row 0 (top) maps to the highest Y.
                int unityRow = meta.rows - 1 - row;
                for (int col = 0; col < meta.cols && index < meta.frame_count; col++)
                {
                    spriteMetas.Add(new SpriteMetaData
                    {
                        name = $"frame_{index:D4}",
                        rect = new Rect(
                            col * (meta.cell_size + meta.padding),
                            unityRow * (meta.cell_size + meta.padding),
                            meta.cell_size,
                            meta.cell_size),
                        alignment = (int)SpriteAlignment.Center,
                        pivot = new Vector2(0.5f, 0.5f),
                    });
                    index++;
                }
            }
            importer.spritesheet = spriteMetas.ToArray();
#pragma warning restore CS0618

            Debug.Log($"[AutoSpriteImporter] Sliced {assetPath} into {spriteMetas.Count} sprite(s) "
                      + $"({meta.cols}x{meta.rows} grid, cell={meta.cell_size}px, fps={meta.fps}) from sidecar metadata.");
        }

        static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            foreach (string str in importedAssets)
            {
                if (IsGeneratedSheet(str))
                {
                    Debug.Log($"[AutoSpriteImporter] Imported sprite sheet: {str}");
                    // AnimationClip generation from the sliced sprites (using
                    // the sidecar's fps hint) is left as a manual step via
                    // the Sprite Editor / Animation window for now.
                }
            }
        }
    }
}
